require('config.options')
require('config.keymaps')
require('plugins.plugins-list')
-- require('config.lazy')

-- -- Plugins
-- vim.pack.add {
--   { src = 'https://github.com/neovim/nvim-lspconfig' },
--   { src = 'https://github.com/mason-org/mason.nvim' },
--   { src = 'https://github.com/mason-org/mason-lspconfig.nvim' },
--   { src = 'https://github.com/nvim-treesitter/nvim-treesitter' },
--   { src = 'https://github.com/m4xshen/autoclose.nvim' },
--   { src = 'https://github.com/catppuccin/nvim' },
--   { src = 'https://github.com/christoomey/vim-tmux-navigator' },
--   { src = 'https://github.com/kylechui/nvim-surround' },
--   { src = 'https://github.com/abecodes/tabout.nvim' },
--   { src = 'https://github.com/saghen/blink.cmp' },
--   { src = 'https://github.com/L3MON4D3/LuaSnip' },
--   { src = 'https://github.com/rafamadriz/friendly-snippets' },
-- }
--
-- -- Iniitalize Plugins
-- require('autoclose').setup({
--   options = {
--     pair_spaces = true
--   }
-- })
-- require("nvim-surround").setup()
-- require("tabout").setup()
-- require("luasnip.loaders.from_vscode").lazy_load()
-- require("blink.cmp").setup({
--   signature = { enabled = true },
--   fuzzy = { implementation = "prefer_rust" },
-- })
-- -- LSP Config
-- require("mason").setup()
-- require("mason-lspconfig").setup({
--   ensure_installed = { "lua_ls", "ts_ls", "svelte", "html", "cssls", "emmet_ls" }
-- })
--
-- vim.lsp.enable("lua_ls", "ts_ls", "svelte", "html", "cssls", "emmet_ls", "tailwindcss")
-- vim.diagnostic.config({
--   -- virtual_lines = true
--   virtual_lines = {
--     current_line = true
--   }
-- })
--
-- require 'nvim-treesitter'.setup({
--   opts = {
--     ensure_installed = { "svelte", "typescript", "javascript", "html", "css" },
--     auto_install = true,
--     highlight = {
--       enable = true,
--     },
--   },
-- })
--
-- vim.api.nvim_create_autocmd({"BufEnter", "BufWinEnter"}, {
--   pattern = {"*.svelte"},
--   callback = function()
--     vim.treesitter.start()
--   end
-- })
--
-- -- Color Scheme
-- vim.cmd.colorscheme "catppuccin"
--
-- -- Vim Settings
-- vim.o.winbar = "%{expand('%:.')}"
-- vim.opt.guicursor = "n-v-c-i:block"
-- vim.o.cursorcolumn = false
-- vim.o.undofile = true
-- vim.o.clipboard = "unnamedplus"
-- vim.o.laststatus = 0
-- vim.opt.expandtab = true
-- vim.opt.tabstop = 2
-- vim.opt.shiftwidth = 2
-- vim.opt.softtabstop = -1
-- vim.o.wrap = false
-- vim.o.scrolloff = 8
-- vim.o.sidescrolloff = 8
-- vim.o.number = true
-- vim.opt.autoindent = true
-- -- vim.opt.smartindent = true
-- vim.o.signcolumn = 'yes:1'
-- vim.o.winborder = "rounded"
--
-- -- LSP Keymaps
-- vim.keymap.set('n', '<leader>f', vim.lsp.buf.format)
-- vim.keymap.set('n', 'gd', vim.lsp.buf.definition)
-- vim.keymap.set('n', 'K', vim.lsp.buf.hover)
-- vim.keymap.set('n', '<leader>r', vim.lsp.buf.rename)
-- vim.keymap.set('n', '<leader>ca', vim.lsp.buf.code_action)
-- vim.keymap.set('n', '[d', vim.diagnostic.goto_prev)
-- vim.keymap.set('n', ']d', vim.diagnostic.goto_next)
-- vim.keymap.set('n', '<leader>ld', vim.diagnostic.open_float)
--
-- -- Quick-use Terminal
-- local term_buf = nil
-- local term_win = nil
--
-- local function toggle_terminal()
--   -- If window exists and is valid, close it
--   if term_win and vim.api.nvim_win_is_valid(term_win) then
--     vim.api.nvim_win_hide(term_win)
--     term_win = nil
--     return
--   end
--
--   -- If buffer doesn't exist or isn't valid, create new terminal
--   if not term_buf or not vim.api.nvim_buf_is_valid(term_buf) then
--     term_buf = vim.api.nvim_create_buf(false, true)
--     vim.api.nvim_buf_call(term_buf, function()
--       vim.fn.termopen(vim.o.shell)
--     end)
--   end
--
--   -- Create the split window
--   vim.cmd('botright split')
--   term_win = vim.api.nvim_get_current_win()
--   vim.api.nvim_win_set_buf(term_win, term_buf)
--   vim.api.nvim_win_set_height(term_win, 12)
--
--   -- Enter insert mode in terminal
--   vim.cmd('startinsert')
-- end
--
-- -- Keybinding to toggle terminal
-- vim.keymap.set({'n', 't'}, '<C-\\>', toggle_terminal, { desc = 'Toggle terminal drawer' })
--
-- -- Optional: escape terminal mode with ESC
-- vim.keymap.set('t', '<Esc>', '<C-\\><C-n>', { desc = 'Exit terminal mode' })
